### ISSUE TITLE
adding unneeded semicolon & breaks standard

### ISSUE THREAD

**Issue by stephenmathieson** [maxogden/standard-format#174] opened 2016-07-19 01:15 UTC
looks like an extra semi is being added when fat arrow function's params are wrapped with parens:

```
~/dev/src/github.com/segmentio/app on canary [!?] ∴ cat x.js
export default () => <div onSomething={(x) => y(x)}><foo /></div>

~/dev/src/github.com/segmentio/app on canary [!?] ∴ ./node_modules/.bin/standard-format x.js > y.js

~/dev/src/github.com/segmentio/app on canary [!?] ∴ ./node_modules/.bin/standard y.js
standard: Use JavaScript Standard Style (http://standardjs.com) 
  /Users/stephenmathieson/dev/src/github.com/segmentio/app/y.js:1:40: Parsing error: Unexpected token ;

~/dev/src/github.com/segmentio/app on canary [!?] ∴ cat y.js 
export default () => <div onSomething={;(x) => y(x)}>
                       <foo />
                     </div>

```

**Comment by carbureted** [comment] 2016-08-07 02:01
+1, makes the formatter unusable for me :(

**Comment by carbureted** [comment] 2016-08-07 08:29
It looks to me like the problem is probably best addressed in https://github.com/millermedeiros/esformatter-semicolon-first

**Comment by millermedeiros** [comment] 2016-08-07 20:23
just released `esformatter-semicolon-first@1.2.0` with the fix!

**Comment by feross** [comment] 2016-08-07 20:30
Thanks!

**Comment by carbureted** [comment] 2016-08-07 21:37
Feross, is the updated package working for you? I'm still getting the same bug when used in standard-format, but not when the esformatter-semicolon-first package is used independently.

**Comment by feross** [comment] 2016-08-07 21:55
@carbureted Yeah, you're right -- it's not working for me either.

Sidenote: @maxogden -- can you please add @millermedeiros to this repo?

**Comment by feross** [comment] 2016-08-07 22:05
Extra sidenote: @carbureted you might try using `standard --fix` (part of the latest standard beta (`npm install standard@beta`) instead of `standard-format`.

**Comment by carbureted** [comment] 2016-08-07 22:29
@feross `standard --fix` is working for me, thanks!

**Comment by feross** [comment] 2016-11-23 19:42
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.

**Closed by feross** 2016-11-23 19:42 UTC
