### ISSUE TITLE
not supports ES2015 Class

### ISSUE THREAD

**Issue by leecade** [maxogden/standard-format#126] opened 2015-10-30 21:52 UTC
```js
export class com extends Component {
  render () {}
}
```

got

```js
export class com extends Component {
  render() {}
}
```

not match standard's rule

**Comment by bcomnes** [comment] 2015-10-30 23:00
I think this is a duplicate of https://github.com/maxogden/standard-format/issues/111  I added some new rules in https://github.com/maxogden/standard-format/pull/125 last night that I hope will help bring better ES6 support to `standard-format`, but I added them in as a noop and have not had a chance to fiddle with them.

**Comment by zeke** [comment] 2015-11-01 03:45
Thanks @bcomnes. Would be awesome to see this fixed.

**Comment by 0x80** [comment] 2015-11-07 08:43
It's also a duplicate of this older one #75. I'd love to see this fixed as well. Currenly I work around it by using esling with the standard rules and overruling that specific one.

```
{
  "parser": "babel-eslint",
  "extends": ["standard", "standard-react"],
  "rules" : {
    "space-before-function-paren": 0
  }
}
```

**Comment by bcomnes** [comment] 2015-11-07 19:15
Hints like this are awesome, I'll try to integrate this this and whatever else i can figure out this weekend.

**Comment by bcomnes** [comment] 2015-11-07 21:01
I couldn't find rule that changes this.  Tracking upstream: https://github.com/millermedeiros/esformatter/issues/384

**Comment by bcomnes** [comment] 2015-11-19 03:52
Another example: https://github.com/feross/standard/issues/337

**Closed by bcomnes** 2015-11-19 03:52 UTC
Labels: bug
