### ISSUE TITLE
ES6 object literal shorthand formatted badly

### ISSUE THREAD

**Issue by Janpot** [maxogden/standard-format#122] opened 2015-10-09 13:53 UTC
Objects defined as follows:

```js
var x = {
  y,
  z
}
```

get formatted like:

```js
var x = {
  y,
z}
```

**Comment by feross** [comment] 2015-10-09 23:37
PR welcome! The issue might be as simple as updating the version of esformatter used to improve ES6 support. Or, perhaps changing one of the rules in the esformatter config file.

**Comment by Flet** [comment] 2015-10-27 16:30
This looks to be a duplicate of https://github.com/maxogden/standard-format/issues/88

**Closed** 2015-10-27 16:31 UTC
